[build]
  command = "npm run build"
  publish = "dist"

# Single Page App: route all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Do not force rewriting of all requests (allows static assets to be served with proper MIME types)
